# Generated by Django 4.0.2 on 2024-01-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_cp_code_product_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='other_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
