# Generated by Django 4.0.2 on 2024-01-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Brand',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
