# Generated by Django 4.0.2 on 2024-01-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Brand',
            new_name='type',
        ),
    ]
