# Generated by Django 4.0.2 on 2024-01-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_brand_category_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='Brand',
        ),
    ]
